Color = int

DEFAULT = 0

BLACK = 1
RED = 2
GREEN = 3
YELLOW = 4
BLUE = 5
MAGENTA = 6
CYAN = 7
WHITE = 8

GRAY = 9
BRIGHT_RED = 10
BRIGHT_GREEN = 11
BRIGHT_YELLOW = 12
BRIGHT_BLUE = 13
BRIGHT_MAGENTA = 14
BRIGHT_CYAN = 15
BRIGHT_WHITE = 16

WHITE_ON_BLACK = 17
WHITE_ON_RED = 18
WHITE_ON_GREEN = 19
WHITE_ON_YELLOW = 20
WHITE_ON_BLUE = 21
WHITE_ON_MAGENTA = 22
WHITE_ON_CYAN = 23
WHITE_ON_WHITE = 24

BLACK_ON_BLACK = 25
BLACK_ON_RED = 26
BLACK_ON_GREEN = 27
BLACK_ON_YELLOW = 28
BLACK_ON_BLUE = 29
BLACK_ON_MAGENTA = 30
BLACK_ON_CYAN = 31
BLACK_ON_WHITE = 32
