[project]
name = "pte"
version = "0.1.3"
description = "A modal command-line text editor written in Python"
authors = [{name = "Jakob Knauer"}]
dynamic = ["dependencies"]

[tool.setuptools.packages.find]
where = ["."]
include = ["pte*"]
namespaces = false

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.black]
line-length = 100
