[project]
name = "pte"
version = "0.1.1"
description = "A modal command-line text editor written in Python"
authors = [{name = "Jakob Knauer"}]

[tool.setuptools.packages.find]
where = ["."]
include = ["pte*"]
namespaces = false
